# Stubs for cereal.apps (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.apps import AppConfig

class CerealAppConfig(AppConfig):
    name: str = ...
